# theme: jekyll-theme-dinky
theme: jekyll-theme-cayman
google_analytics: ['UA-128916623-7']
title: [Install & run Apache Spark on Mac and AWS cloud]
description: [Learn Apache spark by doing hands on]
github:
  home_url: https://rupeshtiwari.com