# theme: jekyll-theme-dinky
theme: jekyll-theme-cayman
google_analytics: ['UA-128916623-7']
title: [Real-time streaming with Apache Kafka & Spark]
description: [Real-time streaming with Apache Kafka & Spark]
github:
  home_url: https://rupeshtiwari.com